### PR TITLE
Fix error when connecting via open-fhir

### PR DESCRIPTION
**Pull request by erikwiffin**

### CODE REVIEW

**Comment by erikwiffin** [comment]
I made this change in production and it's fixing the error.

**Comment by jmandel** [comment]
Thanks! On prod I'm seeing successful but empty responses now.

**Comment by erikwiffin** [comment]
Heh, so that's actually the system behaving as designed, unhelpfully. /api/open-fhir is not authenticated, so it can only access resources with the "public" security tag. I thought all our demo resources had that tag, but apparently not.

We can either change that so that the open endpoint doesn't add any security tags, which feels "bad" for a reference implementation, or we can change demo data loader to add the "public" tag to everything. Thoughts?

**Comment by jmandel** [comment]
Indeed — updating the demo data loader seems like the right move here (and re-running the loader against our prod environment).

**Pull request merged**
